site_name: Desarrollo Web en Entorno Cliente
site_description: Apuntes del módulo de Desarrollo Web en Entorno Cliente de 2.º DAW
site_author: Carlos Alcañiz Carbonell

theme:
  name: material
  language: es
  palette:
    - scheme: default
      primary: orange
      accent: light green
      toggle:
        icon: material/weather-night
        name: Activar modo oscuro
    - scheme: slate
      primary: orange
      accent: light green
      toggle:
        icon: material/weather-sunny
        name: Activar modo claro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search:
      lang: es
      

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

copyright: >
  © 2026-2027 Carlos Alcañiz ·
  Desarrollo Web en Entorno Cliente

extra:
  generator: false
  
extra_css:
  - assets/stylesheets/extra.css

nav:
  - Inicio: index.md
  - UP01:
      - 1. Relación Curricular: up01/01-index.md
      - 2. Introducción: up01/02-introduccion.md
      - 3. Aplicaciones Web: up01/03-aplicaciones-web.md
      - 4. Arquitectura de una aplicación web: up01/04-arquitectura-de-una-aplicacion-web.md
      - 5. Ejecución en cliente y servidor: up01/05-ejecucion-cliente-servidor.md
      - 6. El navegador como entorno de ejecución: up01/06-el-navegador.md
      - 7. Tecnologías de desarrollo web en cliente: up01/07-tecnologias-desarrollo-web-cliente.md
      - 8. Programación mediante guiones: up01/08-programacion-mediante-guiones.md
      - 9. Integración de JavaScript en HTML: up01/09-integracion-javascript-html.md
      - 10. Herramientas de desarrollo y prueba: up01/10-herramientas-de-desarrollo-y-prueba.md
  - UP02:
      - 1. Relación Curricular: up02/01-relacion-curricular.md
      - 2. Introducción: up02/02-introduccion.md
      - 3. Elección del lenguaje: up02/03-eleccion-lenguaje.md
      - 4. Primer programa: up02/04-primer-programa.md
      - 5. Variables y constantes: up02/05-variables-y-constantes.md
      - 6. Tipos de datos: up02/06-tipos-de-datos.md